PRAGMA foreign_keys = on;
.mode columns
.headers on
.nullvalue NULL

CREATE TABLE User (
    ID       INTEGER PRIMARY KEY,
    Username STRING  UNIQUE
                     NOT NULL,
    Password VARCHAR(256) NOT NULL
);


DROP TABLE IF EXISTS Category;
CREATE TABLE Category (
    ID INTEGER PRIMARY KEY
);

DROP TABLE IF EXISTS List;
CREATE TABLE List (
    ID    INTEGER PRIMARY KEY,
    CatID INTEGER REFERENCES Category (ID)
);

DROP TABLE IF EXISTS Task;
CREATE TABLE Task (
    ID     INTEGER PRIMARY KEY,
    ListID INTEGER REFERENCES List (ID)
);

DROP TABLE IF EXISTS UserList;
CREATE TABLE UserList (
    UserID INTEGER REFERENCES User (ID),
    ListID INTEGER REFERENCES List (ID),
    PRIMARY KEY (UserID, ListID)
);
